import type { Metadata } from "next";
import { Roboto, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const vazir = localFont({
//   variable: "--font-vazir",
//   src: [
//     {
//       path: "../fonts/Vazirmatn-Regular.woff2",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../fonts/Vazirmatn-Bold.woff2",
//       weight: "700",
//       style: "normal",
//     },
//   ],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} ${roboto.variable} antialiased`}>
        <Navbar />
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <Footer />
      </body>
    </html>
  );
}
